# Generated by Django 3.1.3 on 2020-12-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201216_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
