# Generated by Django 3.1.3 on 2020-12-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
